//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HToolEx.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HToolExRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HToolExRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HToolEx.Localization.HToolExRes", typeof(HToolExRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening.
        /// </summary>
        public static string DirTypeFastening {
            get {
                return ResourceManager.GetString("DirTypeFastening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loosening.
        /// </summary>
        public static string DirTypeLoosening {
            get {
                return ResourceManager.GetString("DirTypeLoosening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm reset.
        /// </summary>
        public static string EventAlarmReset {
            get {
                return ResourceManager.GetString("EventAlarmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string EventBarcode {
            get {
                return ResourceManager.GetString("EventBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F / L.
        /// </summary>
        public static string EventDir {
            get {
                return ResourceManager.GetString("EventDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string EventError {
            get {
                return ResourceManager.GetString("EventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etc..
        /// </summary>
        public static string EventEtc {
            get {
                return ResourceManager.GetString("EventEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening NG.
        /// </summary>
        public static string EventFastenNg {
            get {
                return ResourceManager.GetString("EventFastenNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening OK.
        /// </summary>
        public static string EventFastenOk {
            get {
                return ResourceManager.GetString("EventFastenOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string EventNone {
            get {
                return ResourceManager.GetString("EventNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset change.
        /// </summary>
        public static string EventPreset {
            get {
                return ResourceManager.GetString("EventPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screw count - 1.
        /// </summary>
        public static string EventScrewCancel {
            get {
                return ResourceManager.GetString("EventScrewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screw count reset.
        /// </summary>
        public static string EventScrewReset {
            get {
                return ResourceManager.GetString("EventScrewReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string GraphDirAll {
            get {
                return ResourceManager.GetString("GraphDirAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string GraphDirBoth {
            get {
                return ResourceManager.GetString("GraphDirBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fasten Only.
        /// </summary>
        public static string GraphDirFasten {
            get {
                return ResourceManager.GetString("GraphDirFasten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loosen Only.
        /// </summary>
        public static string GraphDirLoosen {
            get {
                return ResourceManager.GetString("GraphDirLoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamp.
        /// </summary>
        public static string GraphStepClamp {
            get {
                return ResourceManager.GetString("GraphStepClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torque complete.
        /// </summary>
        public static string GraphStepComplete {
            get {
                return ResourceManager.GetString("GraphStepComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaging.
        /// </summary>
        public static string GraphStepEngaging {
            get {
                return ResourceManager.GetString("GraphStepEngaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening.
        /// </summary>
        public static string GraphStepFasten {
            get {
                return ResourceManager.GetString("GraphStepFasten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free reverse rotation.
        /// </summary>
        public static string GraphStepFreeReverse {
            get {
                return ResourceManager.GetString("GraphStepFreeReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free rotation.
        /// </summary>
        public static string GraphStepFreeRotation {
            get {
                return ResourceManager.GetString("GraphStepFreeRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string GraphStepNone {
            get {
                return ResourceManager.GetString("GraphStepNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevailing start.
        /// </summary>
        public static string GraphStepPrevailingStart {
            get {
                return ResourceManager.GetString("GraphStepPrevailingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation after torque-up.
        /// </summary>
        public static string GraphStepRotateAfterTorqueUp {
            get {
                return ResourceManager.GetString("GraphStepRotateAfterTorqueUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seating.
        /// </summary>
        public static string GraphStepSeating {
            get {
                return ResourceManager.GetString("GraphStepSeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snug torque.
        /// </summary>
        public static string GraphStepSnugTorque {
            get {
                return ResourceManager.GetString("GraphStepSnugTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread tap.
        /// </summary>
        public static string GraphStepThreadTap {
            get {
                return ResourceManager.GetString("GraphStepThreadTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string GraphTypeAngle {
            get {
                return ResourceManager.GetString("GraphTypeAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string GraphTypeCurrent {
            get {
                return ResourceManager.GetString("GraphTypeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current command.
        /// </summary>
        public static string GraphTypeCurrentCmd {
            get {
                return ResourceManager.GetString("GraphTypeCurrentCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string GraphTypeNone {
            get {
                return ResourceManager.GetString("GraphTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snug angle.
        /// </summary>
        public static string GraphTypeSnugAngle {
            get {
                return ResourceManager.GetString("GraphTypeSnugAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string GraphTypeSpeed {
            get {
                return ResourceManager.GetString("GraphTypeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed command.
        /// </summary>
        public static string GraphTypeSpeedCmd {
            get {
                return ResourceManager.GetString("GraphTypeSpeedCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torque.
        /// </summary>
        public static string GraphTypeTorque {
            get {
                return ResourceManager.GetString("GraphTypeTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torque / Angle.
        /// </summary>
        public static string GraphTypeTorqueAngle {
            get {
                return ResourceManager.GetString("GraphTypeTorqueAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string JobEventTypeBack {
            get {
                return ResourceManager.GetString("JobEventTypeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening NG.
        /// </summary>
        public static string JobEventTypeFastenNg {
            get {
                return ResourceManager.GetString("JobEventTypeFastenNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening OK.
        /// </summary>
        public static string JobEventTypeFastenOk {
            get {
                return ResourceManager.GetString("JobEventTypeFastenOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job aborted.
        /// </summary>
        public static string JobEventTypeJobAbort {
            get {
                return ResourceManager.GetString("JobEventTypeJobAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job NG.
        /// </summary>
        public static string JobEventTypeJobNg {
            get {
                return ResourceManager.GetString("JobEventTypeJobNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job OK.
        /// </summary>
        public static string JobEventTypeJobOk {
            get {
                return ResourceManager.GetString("JobEventTypeJobOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset job.
        /// </summary>
        public static string JobEventTypeResetJob {
            get {
                return ResourceManager.GetString("JobEventTypeResetJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset step.
        /// </summary>
        public static string JobEventTypeResetStep {
            get {
                return ResourceManager.GetString("JobEventTypeResetStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string JobEventTypeSkip {
            get {
                return ResourceManager.GetString("JobEventTypeSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step into.
        /// </summary>
        public static string JobEventTypeStepInto {
            get {
                return ResourceManager.GetString("JobEventTypeStepInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step NG.
        /// </summary>
        public static string JobEventTypeStepNg {
            get {
                return ResourceManager.GetString("JobEventTypeStepNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step OK.
        /// </summary>
        public static string JobEventTypeStepOk {
            get {
                return ResourceManager.GetString("JobEventTypeStepOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string JobStepTypeDelay {
            get {
                return ResourceManager.GetString("JobStepTypeDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening.
        /// </summary>
        public static string JobStepTypeFastening {
            get {
                return ResourceManager.GetString("JobStepTypeFastening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string JobStepTypeId {
            get {
                return ResourceManager.GetString("JobStepTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string JobStepTypeInput {
            get {
                return ResourceManager.GetString("JobStepTypeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string JobStepTypeMessage {
            get {
                return ResourceManager.GetString("JobStepTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string JobStepTypeOutput {
            get {
                return ResourceManager.GetString("JobStepTypeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fasten lock.
        /// </summary>
        public static string LockTypeFastenLock {
            get {
                return ResourceManager.GetString("LockTypeFastenLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string LockTypeLock {
            get {
                return ResourceManager.GetString("LockTypeLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loosen lock.
        /// </summary>
        public static string LockTypeLoosenLock {
            get {
                return ResourceManager.GetString("LockTypeLoosenLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string LockTypeUnLock {
            get {
                return ResourceManager.GetString("LockTypeUnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle 1.
        /// </summary>
        public static string LogTypeAngle1 {
            get {
                return ResourceManager.GetString("LogTypeAngle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle 2.
        /// </summary>
        public static string LogTypeAngle2 {
            get {
                return ResourceManager.GetString("LogTypeAngle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle 3.
        /// </summary>
        public static string LogTypeAngle3 {
            get {
                return ResourceManager.GetString("LogTypeAngle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string LogTypeBarcode {
            get {
                return ResourceManager.GetString("LogTypeBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamp torque.
        /// </summary>
        public static string LogTypeClampTorque {
            get {
                return ResourceManager.GetString("LogTypeClampTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string LogTypeDir {
            get {
                return ResourceManager.GetString("LogTypeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LogTypeError {
            get {
                return ResourceManager.GetString("LogTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fasten time.
        /// </summary>
        public static string LogTypeFastenTime {
            get {
                return ResourceManager.GetString("LogTypeFastenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID1.
        /// </summary>
        public static string LogTypeId1 {
            get {
                return ResourceManager.GetString("LogTypeId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID1 name.
        /// </summary>
        public static string LogTypeId1Name {
            get {
                return ResourceManager.GetString("LogTypeId1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID2.
        /// </summary>
        public static string LogTypeId2 {
            get {
                return ResourceManager.GetString("LogTypeId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID2 name.
        /// </summary>
        public static string LogTypeId2Name {
            get {
                return ResourceManager.GetString("LogTypeId2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3.
        /// </summary>
        public static string LogTypeId3 {
            get {
                return ResourceManager.GetString("LogTypeId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3 name.
        /// </summary>
        public static string LogTypeId3Name {
            get {
                return ResourceManager.GetString("LogTypeId3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID4.
        /// </summary>
        public static string LogTypeId4 {
            get {
                return ResourceManager.GetString("LogTypeId4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID4 name.
        /// </summary>
        public static string LogTypeId4Name {
            get {
                return ResourceManager.GetString("LogTypeId4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID5.
        /// </summary>
        public static string LogTypeId5 {
            get {
                return ResourceManager.GetString("LogTypeId5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID5 name.
        /// </summary>
        public static string LogTypeId5Name {
            get {
                return ResourceManager.GetString("LogTypeId5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID6.
        /// </summary>
        public static string LogTypeId6 {
            get {
                return ResourceManager.GetString("LogTypeId6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID6 name.
        /// </summary>
        public static string LogTypeId6Name {
            get {
                return ResourceManager.GetString("LogTypeId6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name.
        /// </summary>
        public static string LogTypeJobName {
            get {
                return ResourceManager.GetString("LogTypeJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG cause.
        /// </summary>
        public static string LogTypeNgCause {
            get {
                return ResourceManager.GetString("LogTypeNgCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset no..
        /// </summary>
        public static string LogTypePreset {
            get {
                return ResourceManager.GetString("LogTypePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevailing torque.
        /// </summary>
        public static string LogTypePrevTorque {
            get {
                return ResourceManager.GetString("LogTypePrevTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain screw.
        /// </summary>
        public static string LogTypeScrews {
            get {
                return ResourceManager.GetString("LogTypeScrews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seating torque.
        /// </summary>
        public static string LogTypeSeatTorque {
            get {
                return ResourceManager.GetString("LogTypeSeatTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snug angle.
        /// </summary>
        public static string LogTypeSnugAngle {
            get {
                return ResourceManager.GetString("LogTypeSnugAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snug torque.
        /// </summary>
        public static string LogTypeSnugTorque {
            get {
                return ResourceManager.GetString("LogTypeSnugTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string LogTypeSpeed {
            get {
                return ResourceManager.GetString("LogTypeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LogTypeStatus {
            get {
                return ResourceManager.GetString("LogTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step name.
        /// </summary>
        public static string LogTypeStepName {
            get {
                return ResourceManager.GetString("LogTypeStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target torque.
        /// </summary>
        public static string LogTypeTargetTorque {
            get {
                return ResourceManager.GetString("LogTypeTargetTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool name.
        /// </summary>
        public static string LogTypeToolName {
            get {
                return ResourceManager.GetString("LogTypeToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted torque.
        /// </summary>
        public static string LogTypeTorque {
            get {
                return ResourceManager.GetString("LogTypeTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string LogTypeUnit {
            get {
                return ResourceManager.GetString("LogTypeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string ModelCmdBarcode {
            get {
                return ResourceManager.GetString("ModelCmdBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string ModelCmdDelay {
            get {
                return ResourceManager.GetString("ModelCmdDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening.
        /// </summary>
        public static string ModelCmdFastening {
            get {
                return ResourceManager.GetString("ModelCmdFastening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string ModelCmdInput {
            get {
                return ResourceManager.GetString("ModelCmdInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ModelCmdNone {
            get {
                return ResourceManager.GetString("ModelCmdNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string ModelCmdOutput {
            get {
                return ResourceManager.GetString("ModelCmdOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active high.
        /// </summary>
        public static string ModelInputTypeActiveHigh {
            get {
                return ResourceManager.GetString("ModelInputTypeActiveHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active low.
        /// </summary>
        public static string ModelInputTypeActiveLow {
            get {
                return ResourceManager.GetString("ModelInputTypeActiveLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ModelInputTypeNone {
            get {
                return ResourceManager.GetString("ModelInputTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status high.
        /// </summary>
        public static string ModelInputTypeStatusHigh {
            get {
                return ResourceManager.GetString("ModelInputTypeStatusHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status low.
        /// </summary>
        public static string ModelInputTypeStatusLow {
            get {
                return ResourceManager.GetString("ModelInputTypeStatusLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On for 0.5 sec.
        /// </summary>
        public static string ModelOutputTypeHalfSec {
            get {
                return ResourceManager.GetString("ModelOutputTypeHalfSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ModelOutputTypeNone {
            get {
                return ResourceManager.GetString("ModelOutputTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ModelOutputTypeOff {
            get {
                return ResourceManager.GetString("ModelOutputTypeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ModelOutputTypeOn {
            get {
                return ResourceManager.GetString("ModelOutputTypeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On for 1.0 sec.
        /// </summary>
        public static string ModelOutputTypeSec {
            get {
                return ResourceManager.GetString("ModelOutputTypeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count value = (A).
        /// </summary>
        public static string MsCmdTypeCount {
            get {
                return ResourceManager.GetString("MsCmdTypeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string MsCmdTypeDelay {
            get {
                return ResourceManager.GetString("MsCmdTypeDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string MsCmdTypeEnd {
            get {
                return ResourceManager.GetString("MsCmdTypeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening.
        /// </summary>
        public static string MsCmdTypeFastening {
            get {
                return ResourceManager.GetString("MsCmdTypeFastening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub if (A).
        /// </summary>
        public static string MsCmdTypeIf {
            get {
                return ResourceManager.GetString("MsCmdTypeIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string MsCmdTypeJump {
            get {
                return ResourceManager.GetString("MsCmdTypeJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loosening.
        /// </summary>
        public static string MsCmdTypeLoosening {
            get {
                return ResourceManager.GetString("MsCmdTypeLoosening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MsCmdTypeNone {
            get {
                return ResourceManager.GetString("MsCmdTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select preset.
        /// </summary>
        public static string MsCmdTypePreset {
            get {
                return ResourceManager.GetString("MsCmdTypePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool alarm reset.
        /// </summary>
        public static string SetInTypeAlarmReset {
            get {
                return ResourceManager.GetString("SetInTypeAlarmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string SetInTypeBack {
            get {
                return ResourceManager.GetString("SetInTypeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string SetInTypeDisable {
            get {
                return ResourceManager.GetString("SetInTypeDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency lock.
        /// </summary>
        public static string SetInTypeEmergency {
            get {
                return ResourceManager.GetString("SetInTypeEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job select 1.
        /// </summary>
        public static string SetInTypeJob1 {
            get {
                return ResourceManager.GetString("SetInTypeJob1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job select 2.
        /// </summary>
        public static string SetInTypeJob2 {
            get {
                return ResourceManager.GetString("SetInTypeJob2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job select 3.
        /// </summary>
        public static string SetInTypeJob3 {
            get {
                return ResourceManager.GetString("SetInTypeJob3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job select 4.
        /// </summary>
        public static string SetInTypeJob4 {
            get {
                return ResourceManager.GetString("SetInTypeJob4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job select 5.
        /// </summary>
        public static string SetInTypeJob5 {
            get {
                return ResourceManager.GetString("SetInTypeJob5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job select 6.
        /// </summary>
        public static string SetInTypeJob6 {
            get {
                return ResourceManager.GetString("SetInTypeJob6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job select 7.
        /// </summary>
        public static string SetInTypeJob7 {
            get {
                return ResourceManager.GetString("SetInTypeJob7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job select 8.
        /// </summary>
        public static string SetInTypeJob8 {
            get {
                return ResourceManager.GetString("SetInTypeJob8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset job.
        /// </summary>
        public static string SetInTypeJobReset {
            get {
                return ResourceManager.GetString("SetInTypeJobReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next job.
        /// </summary>
        public static string SetInTypeNextJob {
            get {
                return ResourceManager.GetString("SetInTypeNextJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous job.
        /// </summary>
        public static string SetInTypePrevJob {
            get {
                return ResourceManager.GetString("SetInTypePrevJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SetInTypeSkip {
            get {
                return ResourceManager.GetString("SetInTypeSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset step.
        /// </summary>
        public static string SetInTypeStepReset {
            get {
                return ResourceManager.GetString("SetInTypeStepReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string SetOutTypeAlarm {
            get {
                return ResourceManager.GetString("SetOutTypeAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string SetOutTypeDisable {
            get {
                return ResourceManager.GetString("SetOutTypeDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening NG.
        /// </summary>
        public static string SetOutTypeFastenNg {
            get {
                return ResourceManager.GetString("SetOutTypeFastenNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastening OK.
        /// </summary>
        public static string SetOutTypeFastenOk {
            get {
                return ResourceManager.GetString("SetOutTypeFastenOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job NG.
        /// </summary>
        public static string SetOutTypeJobNg {
            get {
                return ResourceManager.GetString("SetOutTypeJobNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job OK.
        /// </summary>
        public static string SetOutTypeJobOk {
            get {
                return ResourceManager.GetString("SetOutTypeJobOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string SetOutTypeReady {
            get {
                return ResourceManager.GetString("SetOutTypeReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step NG.
        /// </summary>
        public static string SetOutTypeStepNg {
            get {
                return ResourceManager.GetString("SetOutTypeStepNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step OK.
        /// </summary>
        public static string SetOutTypeStepOk {
            get {
                return ResourceManager.GetString("SetOutTypeStepOk", resourceCulture);
            }
        }
    }
}
