<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageId>Hantas.HTool.Core</PackageId>
        <Title>HTool.Core</Title>
        <Version>2.0.0-beta.2</Version>
        <PackageVersion>2.0.0-beta.2</PackageVersion>
        <Company>HANTAS</Company>
        <Authors>Eloiz</Authors>
        <Description>Core utilities and domain types for HANTAS tool communication libraries.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Update="README.md">
            <PackagePath>\</PackagePath>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.IO.Hashing" Version="10.0.8" />
    </ItemGroup>

</Project>
