//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HToolEx.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HToolExRes_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HToolExRes_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HToolEx.Localization.HToolExRes.fr", typeof(HToolExRes_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage.
        /// </summary>
        internal static string DirTypeFastening {
            get {
                return ResourceManager.GetString("DirTypeFastening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dévissage.
        /// </summary>
        internal static string DirTypeLoosening {
            get {
                return ResourceManager.GetString("DirTypeLoosening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZ Alarme.
        /// </summary>
        internal static string EventAlarmReset {
            get {
                return ResourceManager.GetString("EventAlarmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes-barres.
        /// </summary>
        internal static string EventBarcode {
            get {
                return ResourceManager.GetString("EventBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V / D.
        /// </summary>
        internal static string EventDir {
            get {
                return ResourceManager.GetString("EventDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string EventError {
            get {
                return ResourceManager.GetString("EventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres.
        /// </summary>
        internal static string EventEtc {
            get {
                return ResourceManager.GetString("EventEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage NOK.
        /// </summary>
        internal static string EventFastenNg {
            get {
                return ResourceManager.GetString("EventFastenNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage OK.
        /// </summary>
        internal static string EventFastenOk {
            get {
                return ResourceManager.GetString("EventFastenOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string EventNone {
            get {
                return ResourceManager.GetString("EventNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chgt programme.
        /// </summary>
        internal static string EventPreset {
            get {
                return ResourceManager.GetString("EventPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décompte dernier vissage Ok.
        /// </summary>
        internal static string EventScrewCancel {
            get {
                return ResourceManager.GetString("EventScrewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZ comptage vis.
        /// </summary>
        internal static string EventScrewReset {
            get {
                return ResourceManager.GetString("EventScrewReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout.
        /// </summary>
        internal static string GraphDirAll {
            get {
                return ResourceManager.GetString("GraphDirAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux.
        /// </summary>
        internal static string GraphDirBoth {
            get {
                return ResourceManager.GetString("GraphDirBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seulement vissage.
        /// </summary>
        internal static string GraphDirFasten {
            get {
                return ResourceManager.GetString("GraphDirFasten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seulement dévisser.
        /// </summary>
        internal static string GraphDirLoosen {
            get {
                return ResourceManager.GetString("GraphDirLoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage.
        /// </summary>
        internal static string GraphStepFasten {
            get {
                return ResourceManager.GetString("GraphStepFasten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string GraphStepNone {
            get {
                return ResourceManager.GetString("GraphStepNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string GraphTypeAngle {
            get {
                return ResourceManager.GetString("GraphTypeAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courant.
        /// </summary>
        internal static string GraphTypeCurrent {
            get {
                return ResourceManager.GetString("GraphTypeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consigne de courant.
        /// </summary>
        internal static string GraphTypeCurrentCmd {
            get {
                return ResourceManager.GetString("GraphTypeCurrentCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string GraphTypeNone {
            get {
                return ResourceManager.GetString("GraphTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle controlé.
        /// </summary>
        internal static string GraphTypeSnugAngle {
            get {
                return ResourceManager.GetString("GraphTypeSnugAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitesse.
        /// </summary>
        internal static string GraphTypeSpeed {
            get {
                return ResourceManager.GetString("GraphTypeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consigne de vitesse.
        /// </summary>
        internal static string GraphTypeSpeedCmd {
            get {
                return ResourceManager.GetString("GraphTypeSpeedCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple.
        /// </summary>
        internal static string GraphTypeTorque {
            get {
                return ResourceManager.GetString("GraphTypeTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple / Angle.
        /// </summary>
        internal static string GraphTypeTorqueAngle {
            get {
                return ResourceManager.GetString("GraphTypeTorqueAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        internal static string JobEventTypeBack {
            get {
                return ResourceManager.GetString("JobEventTypeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage NOK.
        /// </summary>
        internal static string JobEventTypeFastenNg {
            get {
                return ResourceManager.GetString("JobEventTypeFastenNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage OK.
        /// </summary>
        internal static string JobEventTypeFastenOk {
            get {
                return ResourceManager.GetString("JobEventTypeFastenOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job NOK.
        /// </summary>
        internal static string JobEventTypeJobNg {
            get {
                return ResourceManager.GetString("JobEventTypeJobNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job OK.
        /// </summary>
        internal static string JobEventTypeJobOk {
            get {
                return ResourceManager.GetString("JobEventTypeJobOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZ Job.
        /// </summary>
        internal static string JobEventTypeResetJob {
            get {
                return ResourceManager.GetString("JobEventTypeResetJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZ étape.
        /// </summary>
        internal static string JobEventTypeResetStep {
            get {
                return ResourceManager.GetString("JobEventTypeResetStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauter.
        /// </summary>
        internal static string JobEventTypeSkip {
            get {
                return ResourceManager.GetString("JobEventTypeSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape NOK.
        /// </summary>
        internal static string JobEventTypeStepNg {
            get {
                return ResourceManager.GetString("JobEventTypeStepNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape OK.
        /// </summary>
        internal static string JobEventTypeStepOk {
            get {
                return ResourceManager.GetString("JobEventTypeStepOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attente.
        /// </summary>
        internal static string JobStepTypeDelay {
            get {
                return ResourceManager.GetString("JobStepTypeDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage.
        /// </summary>
        internal static string JobStepTypeFastening {
            get {
                return ResourceManager.GetString("JobStepTypeFastening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string JobStepTypeId {
            get {
                return ResourceManager.GetString("JobStepTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée.
        /// </summary>
        internal static string JobStepTypeInput {
            get {
                return ResourceManager.GetString("JobStepTypeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string JobStepTypeMessage {
            get {
                return ResourceManager.GetString("JobStepTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortie.
        /// </summary>
        internal static string JobStepTypeOutput {
            get {
                return ResourceManager.GetString("JobStepTypeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serrure.
        /// </summary>
        internal static string LockTypeLock {
            get {
                return ResourceManager.GetString("LockTypeLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déverrouiller.
        /// </summary>
        internal static string LockTypeUnLock {
            get {
                return ResourceManager.GetString("LockTypeUnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle 1.
        /// </summary>
        internal static string LogTypeAngle1 {
            get {
                return ResourceManager.GetString("LogTypeAngle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle 2.
        /// </summary>
        internal static string LogTypeAngle2 {
            get {
                return ResourceManager.GetString("LogTypeAngle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle 3.
        /// </summary>
        internal static string LogTypeAngle3 {
            get {
                return ResourceManager.GetString("LogTypeAngle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes-barres.
        /// </summary>
        internal static string LogTypeBarcode {
            get {
                return ResourceManager.GetString("LogTypeBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple de serrage.
        /// </summary>
        internal static string LogTypeClampTorque {
            get {
                return ResourceManager.GetString("LogTypeClampTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sens.
        /// </summary>
        internal static string LogTypeDir {
            get {
                return ResourceManager.GetString("LogTypeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string LogTypeError {
            get {
                return ResourceManager.GetString("LogTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps vissage.
        /// </summary>
        internal static string LogTypeFastenTime {
            get {
                return ResourceManager.GetString("LogTypeFastenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du Job.
        /// </summary>
        internal static string LogTypeJobName {
            get {
                return ResourceManager.GetString("LogTypeJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes-barres.
        /// </summary>
        internal static string ModelCmdBarcode {
            get {
                return ResourceManager.GetString("ModelCmdBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délai.
        /// </summary>
        internal static string ModelCmdDelay {
            get {
                return ResourceManager.GetString("ModelCmdDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage.
        /// </summary>
        internal static string ModelCmdFastening {
            get {
                return ResourceManager.GetString("ModelCmdFastening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée.
        /// </summary>
        internal static string ModelCmdInput {
            get {
                return ResourceManager.GetString("ModelCmdInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string ModelCmdNone {
            get {
                return ResourceManager.GetString("ModelCmdNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortie.
        /// </summary>
        internal static string ModelCmdOutput {
            get {
                return ResourceManager.GetString("ModelCmdOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif haut.
        /// </summary>
        internal static string ModelInputTypeActiveHigh {
            get {
                return ResourceManager.GetString("ModelInputTypeActiveHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif bas.
        /// </summary>
        internal static string ModelInputTypeActiveLow {
            get {
                return ResourceManager.GetString("ModelInputTypeActiveLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string ModelInputTypeNone {
            get {
                return ResourceManager.GetString("ModelInputTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau haut.
        /// </summary>
        internal static string ModelInputTypeStatusHigh {
            get {
                return ResourceManager.GetString("ModelInputTypeStatusHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau bas.
        /// </summary>
        internal static string ModelInputTypeStatusLow {
            get {
                return ResourceManager.GetString("ModelInputTypeStatusLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulsion de 0,5 s.
        /// </summary>
        internal static string ModelOutputTypeHalfSec {
            get {
                return ResourceManager.GetString("ModelOutputTypeHalfSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string ModelOutputTypeNone {
            get {
                return ResourceManager.GetString("ModelOutputTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ModelOutputTypeOff {
            get {
                return ResourceManager.GetString("ModelOutputTypeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ModelOutputTypeOn {
            get {
                return ResourceManager.GetString("ModelOutputTypeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulsion de 1,0 s.
        /// </summary>
        internal static string ModelOutputTypeSec {
            get {
                return ResourceManager.GetString("ModelOutputTypeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur Compteur (A).
        /// </summary>
        internal static string MsCmdTypeCount {
            get {
                return ResourceManager.GetString("MsCmdTypeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délai.
        /// </summary>
        internal static string MsCmdTypeDelay {
            get {
                return ResourceManager.GetString("MsCmdTypeDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        internal static string MsCmdTypeEnd {
            get {
                return ResourceManager.GetString("MsCmdTypeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage.
        /// </summary>
        internal static string MsCmdTypeFastening {
            get {
                return ResourceManager.GetString("MsCmdTypeFastening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décompte (A).
        /// </summary>
        internal static string MsCmdTypeIf {
            get {
                return ResourceManager.GetString("MsCmdTypeIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saut.
        /// </summary>
        internal static string MsCmdTypeJump {
            get {
                return ResourceManager.GetString("MsCmdTypeJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dévissage.
        /// </summary>
        internal static string MsCmdTypeLoosening {
            get {
                return ResourceManager.GetString("MsCmdTypeLoosening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string MsCmdTypeNone {
            get {
                return ResourceManager.GetString("MsCmdTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner préréglage.
        /// </summary>
        internal static string MsCmdTypePreset {
            get {
                return ResourceManager.GetString("MsCmdTypePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialisation de l&apos;alarme de l&apos;outil.
        /// </summary>
        internal static string SetInTypeAlarmReset {
            get {
                return ResourceManager.GetString("SetInTypeAlarmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        internal static string SetInTypeBack {
            get {
                return ResourceManager.GetString("SetInTypeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver.
        /// </summary>
        internal static string SetInTypeDisable {
            get {
                return ResourceManager.GetString("SetInTypeDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verrouillage d&apos;urgence des visseuses.
        /// </summary>
        internal static string SetInTypeEmergency {
            get {
                return ResourceManager.GetString("SetInTypeEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job sélectionné 1.
        /// </summary>
        internal static string SetInTypeJob1 {
            get {
                return ResourceManager.GetString("SetInTypeJob1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job sélectionné 2.
        /// </summary>
        internal static string SetInTypeJob2 {
            get {
                return ResourceManager.GetString("SetInTypeJob2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job sélectionné 3.
        /// </summary>
        internal static string SetInTypeJob3 {
            get {
                return ResourceManager.GetString("SetInTypeJob3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job sélectionné 4.
        /// </summary>
        internal static string SetInTypeJob4 {
            get {
                return ResourceManager.GetString("SetInTypeJob4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job sélectionné 5.
        /// </summary>
        internal static string SetInTypeJob5 {
            get {
                return ResourceManager.GetString("SetInTypeJob5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job sélectionné 6.
        /// </summary>
        internal static string SetInTypeJob6 {
            get {
                return ResourceManager.GetString("SetInTypeJob6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job sélectionné 7.
        /// </summary>
        internal static string SetInTypeJob7 {
            get {
                return ResourceManager.GetString("SetInTypeJob7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job sélectionné 8.
        /// </summary>
        internal static string SetInTypeJob8 {
            get {
                return ResourceManager.GetString("SetInTypeJob8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZ Job.
        /// </summary>
        internal static string SetInTypeJobReset {
            get {
                return ResourceManager.GetString("SetInTypeJobReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job suivant.
        /// </summary>
        internal static string SetInTypeNextJob {
            get {
                return ResourceManager.GetString("SetInTypeNextJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job précédent.
        /// </summary>
        internal static string SetInTypePrevJob {
            get {
                return ResourceManager.GetString("SetInTypePrevJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        internal static string SetInTypeSkip {
            get {
                return ResourceManager.GetString("SetInTypeSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAZ étape.
        /// </summary>
        internal static string SetInTypeStepReset {
            get {
                return ResourceManager.GetString("SetInTypeStepReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarme.
        /// </summary>
        internal static string SetOutTypeAlarm {
            get {
                return ResourceManager.GetString("SetOutTypeAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver.
        /// </summary>
        internal static string SetOutTypeDisable {
            get {
                return ResourceManager.GetString("SetOutTypeDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage NOK.
        /// </summary>
        internal static string SetOutTypeFastenNg {
            get {
                return ResourceManager.GetString("SetOutTypeFastenNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissage OK.
        /// </summary>
        internal static string SetOutTypeFastenOk {
            get {
                return ResourceManager.GetString("SetOutTypeFastenOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job NOK.
        /// </summary>
        internal static string SetOutTypeJobNg {
            get {
                return ResourceManager.GetString("SetOutTypeJobNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job OK.
        /// </summary>
        internal static string SetOutTypeJobOk {
            get {
                return ResourceManager.GetString("SetOutTypeJobOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt.
        /// </summary>
        internal static string SetOutTypeReady {
            get {
                return ResourceManager.GetString("SetOutTypeReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape NOK.
        /// </summary>
        internal static string SetOutTypeStepNg {
            get {
                return ResourceManager.GetString("SetOutTypeStepNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape OK.
        /// </summary>
        internal static string SetOutTypeStepOk {
            get {
                return ResourceManager.GetString("SetOutTypeStepOk", resourceCulture);
            }
        }
    }
}
