<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageId>Hantas.HTool.Format</PackageId>
        <Title>HTool.Format</Title>
        <Version>1.0.0</Version>
        <PackageVersion>1.0.0</PackageVersion>
        <Company>HANTAS</Company>
        <Authors>Eloiz</Authors>
        <Description>Data parsing and format classes for HANTAS tool communication libraries.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Update="README.md">
            <PackagePath>\</PackagePath>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HTool.Core\HTool.Core.csproj"/>
    </ItemGroup>

</Project>
