<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageId>Hantas.HTool</PackageId>
        <Title>HTool</Title>
        <Version>1.0.0</Version>
        <PackageVersion>1.0.0</PackageVersion>
        <Company>HANTAS</Company>
        <Authors>Eloiz</Authors>
        <Description>Unified MODBUS communication library for HANTAS tools. Supports direct RTU/TCP and PRO X gateway connections through a transparent abstraction layer.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <LangVersion>12</LangVersion>
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Tester</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentFTP" Version="53.0.2"/>
        <PackageReference Include="System.IO.Ports" Version="10.0.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HTool.Core\HTool.Core.csproj"/>
        <ProjectReference Include="..\HTool.Format\HTool.Format.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="README.md">
            <PackagePath>\</PackagePath>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

</Project>
